export const T = {
    SET_LOGIN_USER_INFO: "SET_LOGIN_USER_INFO",
    SET_LOGIN_GUIDE_LAYER: "SET_LOGIN_GUIDE_LAYER",
    CHANGE_HEADER_TITLE: "CHANGE_HEADER_TITLE",
    SET_THEME_GROUP_LIST: "SET_THEME_GROUP_LIST",
};
